### ISSUE TITLE
Use lombok maven plugin instead of getter/setter

### ISSUE THREAD

**Issue by 0001vrn** [adriancole/zipkin-security#4]
Use the Lombok Maven plugin:
- https://github.com/adriancole/zipkin-security/blob/master/src/main/java/zipkin2/autoconfigure/security/ZipkinSecurityProperties.java

**Comment by adriancole** [comment]
lombok is overkill for an example, and has some IDE side-effects which aren't always intuitive, but you can feel free to use it in your version of this!
